Module6 task2
htmlacademy-php/414045-doingsdone-12 pull request #11
Opened 2021-03-26 14:31 UTC by Archer039

2021-03-29 10:02 UTC, mihan007 requested changes

2021-03-29 10:02 UTC, mihan007 commented on add.php
> +if ($_SERVER['REQUEST_METHOD'] == 'POST') {
- я бы вынес все валидации в отдельные функции.
- и сделал общую функцию validate, которая возвращает в этот скрипт массив $error

Цель этих действий - уменьшить размер скрипта и сделать его легче к восприятию. Мы пишем код не для компьютера, а для людей, которые будут его развивать

2021-03-29 10:02 UTC, mihan007 commented on add.php
> +        $file_url = null;
это тоже в отдельную фукцию

2021-03-29 10:02 UTC, mihan007 commented on add.php
> +        header('Location: http://414045-doingsdone-12/');
header поддерживает относительные адреса. если их использовать, то код будет более приспособленным к переносу на любые домены. я бы изменил

2021-03-29 10:02 UTC, mihan007 commented on add.php
> +    } else {
else - это признак того, что код сложный. я обычно делаю проверку на противоположное условие. если оно выполнилось, то показываю ошибку и завершаю скрипт. а дальше уже без else пишу

примерно так
```
if ($errors) {
  $_GET['page'] = 'add_task';
   require_once 'index.php';
   exit(1);
}
```

2021-03-29 10:02 UTC, mihan007 commented on functions/check.php
> +if (isset($_GET['id_chosen_project'])){
и опять же вынесение этой непростой логики в отдельную функцию упростит код

2021-03-29 10:02 UTC, mihan007 commented on functions/functions.php
> +require_once ('./functions/helpers.php'); //функции от создателей курса
правильный ход. обычно файл с функциями, которые загружаются на каждой странице называется bootstrap.php

2021-03-29 10:02 UTC, mihan007 commented on functions/projects_and_tasks.php
> +function is_importance_task($task_time): bool
importance - существительное. тут больше подходит is_task_important

2021-03-29 10:02 UTC, mihan007 commented on index.php
> +    if (filter($_GET['page']) == 'add_task') {
- данные, которые приходят в GET обычно не фильтруют
- эти 2 if можно упростить за счет оператора ??

2021-03-29 10:02 UTC, mihan007 commented on templates/main.php
> +                    <a class="download-link" href="<?= filter($task['file_src']); ?>"><?= filter($task['file_name']); ?></a>
- фильтрация используется для вывода данных, которые ввел пользователь. например, когда ты берешь сущность из базы. во всех остальных случаях она не нужна. 
- тут $task['file_src'] ты сам создаешь перед выводом шаблоне. его фильтровать не нужно

2021-03-31 16:40 UTC, mihan007 requested changes

2021-03-31 16:40 UTC, mihan007 commented on functions/check.php
> +        return true;
- может быть false?
- попробуй упростить до одного выражения вида
```return $date && check_format_date($date)```

2021-03-31 16:40 UTC, mihan007 commented on functions/projects_and_tasks.php
> +    if (isset($_GET['id_chosen_project']) && $id_project == $_GET['id_chosen_project']) {
тоже упрости до одного выражения. и тогда у тебя будет возвращаться строго true или false. а то сейчас либо true, либо null

2021-03-31 16:40 UTC, mihan007 commented on functions/projects_and_tasks.php
> +function is_importance_task($task_time): bool
@Archer039 пропустил?

2021-03-31 18:30 UTC, Archer039 commented on functions/projects_and_tasks.php
> +function is_importance_task($task_time): bool
Да... просмотрел...

2021-03-31 19:42 UTC, Archer039 commented on functions/check.php
> +        return true;
Тогда логика ломается, у нас дата не обязательный атрибут, но если она есть, тогда должна быть в нужном формате. А так получится что она обязательно нужна.

Мне такое нагромождение как-то тоже не нравится но лучше не придумал...

2021-04-01 08:14 UTC, mihan007 requested changes
Хорошая работы. Ключевые моменты, которые помогут улучшить счет,
1. Ты многое фильтруешь на стороне PHP после получения набора данных из базых. Это неверно. Надо всю фильтрацию делать на стороне SQL
2. Не только фильтрацию, но и подсчет на стороне базы. Как, например, подсчет количества задач в проекте
3. Упростить конструкции с else
4. Упростить if
5. Переформатировать в PSR-12

2021-04-01 08:14 UTC, mihan007 commented on functions/check.php
> +        return true;
Тогда можно опять же избежать else.
```
if (!$date) {
  return true;
}
return check_format_date($date);
```

У меня есть правило - вижу **else** - значит, можно упростить

2021-04-01 08:14 UTC, mihan007 commented on functions/check.php
> +function validate($user_id, $task_name, $project_id, $task_date){
есть стандарт оформления кода PSR-12. его придерживаются практически во всех серьезных проектах

согласно нему скобка, открывающая функцию, должна быть с новой строки. Рекомендую
1. настроить соблюдение PSR-12 в PhpStorm
2. изучить сам стандарт https://redwerk.jobs/blog/psr-12-%D0%BF%D0%B5%D1%80%D0%B5%D0%B2%D0%BE%D0%B4-%D1%80%D0%B0%D1%81%D1%88%D0%B8%D1%80%D0%B5%D0%BD%D0%BD%D0%BE%D0%B3%D0%BE-%D1%81%D1%82%D0%B0%D0%BD%D0%B4%D0%B0%D1%80%D1%82%D0%B0-%D0%BE%D1%84%D0%BE/
3. поправить все функции в соответствии с **4.4 Методы и функции**. Это поможет сделать сам PhpStorm, когда его настроишь

2021-04-01 08:14 UTC, mihan007 commented on functions/projects_and_tasks.php
> +    } else {
опять же else - надо менять. в этом случае реализуем ранный выход от обратного
```
if (!isset($_GET['id_chosen_project'])) {
    return $tasks;
}
$id_project = $_GET['id_chosen_project'];
...
```

2021-04-01 08:14 UTC, mihan007 commented on functions/check.php
> +        } else {
**else** - меняем логику.

2021-04-01 08:14 UTC, mihan007 commented on functions/check.php
> +        if ($_GET['id_chosen_project'] > count(get_projects($current_user_id)) && !is_int($_GET['id_chosen_project'])){
1. такое громоздкое условие разделяют на части
2. $_GET['id_chosen_project'] > count(get_projects($current_user_id) - не очень верно. у тебя может быть у пользователя 1 проект с id=10. Тогда у тебя получится $_GET['id_chosen_project'] = 10, это больше чем count = 1 и выдаст 404. что неверно
3. Я бы сделал запрос в базу на поиск проекта с нужным id и нужным пользователем. Если его в базе нет, то 404.

2021-04-01 08:14 UTC, mihan007 commented on functions/check.php
> +        return true;
1. PSR-12 открытие функции
2. тут if не нужен, упростить

2021-04-01 08:14 UTC, mihan007 commented on functions/check.php
> +    $projects = get_projects($user_id);
1. PSR-12 открытие функции

2021-04-01 08:14 UTC, mihan007 commented on functions/connect.php
> +    print("Ошибка подключения к БД: " . mysqli_connect_error());
PSR-12 открытие функции и дальше все функции

2021-04-01 08:14 UTC, mihan007 commented on functions/projects_and_tasks.php
> +    return (isset($_GET['id_chosen_project']) && $id_project == $_GET['id_chosen_project']) ? true : false;
`? true : false;` не надо, он итак вернет это

2021-04-01 08:14 UTC, mihan007 commented on functions/projects_and_tasks.php
> +    $tasks = get_tasks($current_user_id);
ты при запросе задач сразу делай запрос с учетом $_GET['id_chosen_project']. на стороне php не надо фильтровать так, надо на сторону mysql такую логику держать

2021-04-01 08:14 UTC, mihan007 commented on functions/projects_and_tasks.php
> +    return array_reduce($tasks, function ($carry, $item) {
переделай эту функцию на sql, там у тебя будет выборка проектов и count(tasks) и group by

2021-04-01 08:14 UTC, mihan007 commented on functions/check.php
> +function validate_project($project_id, $user_id) {
и опять же тут надо делать запрос в базу сразу с учетом project_id и user_id. если такой проект есть, то валидация прошла. если нет - то не прошла.

2021-04-06 10:43 UTC, mihan007 requested changes
Привет! Отлично потрудился. Еще пару мелочей шлифанем

2021-04-06 10:43 UTC, mihan007 commented on functions/check.php
> +function check_selected_project_id($current_user_id)
не увидел использования этой функции. лишняя? убираем?

2021-04-06 10:43 UTC, mihan007 commented on functions/projects_and_tasks.php
> +    $tasks = get_tasks($current_user_id);
@Archer039 это замечание не исправлено

2021-04-06 10:43 UTC, mihan007 commented on functions/projects_and_tasks.php
> +    $file_url = save_file();
а если файл не сохранился?

2021-04-06 10:43 UTC, mihan007 commented on functions/projects_and_tasks.php
> +    if (!$task_date) {
в объявлении функции сделай task_date по умолчанию null и этой проверки уже не надо будет

2021-04-06 10:43 UTC, mihan007 commented on functions/queries.php
> +        array_push($projects, array_combine($new_key, $project));
хорошее решение

2021-04-06 10:43 UTC, mihan007 commented on functions/queries.php
> +    $tasks_result = mysqli_fetch_all($result_sql);
в этой функции можно удобно вернуть ответ в виде ассоциативного массива и вместо ```$task_result[4]``` ты сможешь обращаться $task_result['file_src']

просмотри везде, где есть ```mysqli_fetch_all``` и поправь, пожалуйста

https://www.php.net/manual/ru/mysqli-result.fetch-all.php

2021-04-06 11:07 UTC, Archer039 commented on functions/check.php
> +function check_selected_project_id($current_user_id)
Да, я забыл что уже есть функция для проверки id проекта

2021-04-06 21:47 UTC, Archer039 commented on functions/check.php
> +function check_selected_project_id($current_user_id)
Нет, забыл её вызвать)

2021-04-06 21:47 UTC, Archer039 commented on functions/projects_and_tasks.php
> +    $file_url = save_file();
Добавил проверку на ошибки

2021-04-07 09:41 UTC, Archer039 commented on functions/projects_and_tasks.php
> +    if (!$task_date) {
там проблема в том, что если дата не выбрана нам передаётся пустая строка, а не null, и sql при попытке передать пустую строку в timestamp выдаёт ошибку типа данных Incorrect datetime value: '' for column 'time_end' at row 1. Я перенёс условие в запрос и переписал, чтобы было понятнее.

2021-04-07 17:33 UTC, mihan007 approved these changes
По красоте получилось. Молодец!

2021-04-07 17:33 UTC, merged