Аутентифицируемся на сайте
htmlacademy-php/414045-doingsdone-12 pull request #13
Opened 2021-04-20 14:58 UTC by Archer039

2021-04-21 14:26 UTC, mihan007 requested changes
Немного полировки и гуд

2021-04-21 14:26 UTC, mihan007 commented on index.php
> +session_start();
унеси это в bootstap.php

2021-04-21 14:26 UTC, mihan007 commented on index.php
>  require_once(__DIR__ . '/functions/functions.php');
это надо загружать в bootstrap.php, а его самого уже в каждом скрипте

2021-04-21 14:26 UTC, mihan007 commented on pages/add.php
> +$current_user_id = $_SESSION['user_id'];
в bootstrap.php

2021-04-21 14:26 UTC, mihan007 commented on pages/auth.php
> +        $layout_data = get_layout_data(errors: $errors);
php 8, круто)

2021-04-21 14:26 UTC, mihan007 commented on pages/auth.php
> +    session_start();
это у тебя уедет в bootstrap.php

2021-04-21 14:26 UTC, mihan007 commented on pages/logout.php
> +session_start();
в bootstrap.php

2021-04-21 14:26 UTC, mihan007 commented on pages/registration.php
> +    session_start();
boostrap.php

2021-04-21 14:26 UTC, mihan007 commented on templates/layout.php
> +<body <?= !isset($_SESSION['user_id']) ? 'class="body-background"' : '' ?>>
шаблон вообще ничего не должен знать про $_SESSION, тебе надо параметр user_id уже сюда передавать при подключении шаблона. и далее аналогично.

приучи себя к тому, что шаблон работает только с данными, которые ему явно передали. он не должен никуда больше ходить - ни в SESSION, ни в GET, ни в POST. только данные, которые ему явно передали

2021-04-21 14:26 UTC, mihan007 commented on pages/add.php
> +        $layout_data = get_layout_data($errors);
нужна консистентность - если ты передаешь в get_layout_data через name params из php 8, то делай это везде. или нигде) главное, чтобы единообразно

2021-04-23 07:34 UTC, mihan007 requested changes
Еще по мелочи

2021-04-23 07:34 UTC, mihan007 commented on bootstrap.php
> +session_start();
забыл унести в bootstrap?

2021-04-23 07:34 UTC, mihan007 commented on pages/registration.php
> +    session_start();
забыл унести в bootstrap?

2021-04-23 08:43 UTC, Archer039 commented on bootstrap.php
> +session_start();
Так это и есть bootstrap.php

2021-04-23 09:29 UTC, mihan007 approved these changes
🤘

2021-04-23 09:29 UTC, mihan007 commented on bootstrap.php
> +session_start();
тупанул я))

2021-04-23 09:29 UTC, merged