Реализуем полнотекстовый поиск
htmlacademy-php/414045-doingsdone-12 pull request #14
Opened 2021-04-26 14:19 UTC by Archer039

2021-04-26 15:18 UTC, mihan007 requested changes
Хорошая работа. Полируем и вперед!

2021-04-26 15:18 UTC, mihan007 commented on functions/projects_and_tasks.php
>      if (!isset($_GET['id_chosen_project'])) {
лучше вынеси в начало функции определение id проекта и потом его используй
```
$chosenProject = $_GET['id_chosen_project'] ?? null;
get_user_tasks($chosenProject);
```
А потом уже в самой функции `get_user_tasks` в зависимости от chosenProject строй разные запросы

2021-04-26 15:18 UTC, mihan007 commented on functions/data.php
> +    $search_error_message = "";
Когда результаты не найдены, то это всё же не ошибка. Я бы назвал тут по-другому, типа search_error_result.

2021-04-26 15:18 UTC, mihan007 commented on functions/data.php
> +    $tasks = $found_tasks ?? show_tasks();
можно проще
```
$tasks = search_task() ?? show_tasks();
```

2021-04-26 15:18 UTC, mihan007 commented on functions/queries.php
> +    $user_id = $_SESSION['user_id'];
так не надо делать. получение id юзера это точно не задача функции, получающей список задач. точно не ее зона ответственности. определи user_id в месте, где вызывается эта функция и передавай сюда на вход

2021-04-26 15:18 UTC, mihan007 commented on functions/queries.php
> +    $user_id = $_SESSION['user_id'];
передаем извне

2021-04-26 15:18 UTC, mihan007 commented on functions/search.php
> +    if ($_SERVER['REQUEST_METHOD'] == "GET" && isset($_GET['search'])) {
тут можно проще
```
$searchString = $_GET['search'] ?? null;
```
и потом проверяй
```
if ($searchString)
{
...
}
```

2021-04-26 15:18 UTC, mihan007 commented on functions/search.php
> +        $task_name = trim($_GET['search'], " ");
в trim " " вторым параметром является параметром по умолчанию, то есть передавать его не надо

2021-04-27 07:51 UTC, Archer039 commented on functions/projects_and_tasks.php
>      if (!isset($_GET['id_chosen_project'])) {
Да, так проще, причем у меня и так уже есть два запроса в get_user_tasks

2021-04-27 11:57 UTC, mihan007 requested changes
Хорошо проработал. Пойдем глубже. Сделаем оптимизацию по ресурсам и познакомимся с понятием "чистая" функция

2021-04-27 11:57 UTC, mihan007 commented on functions/data.php
> +    $tasks = search_task($user_id) ?? show_tasks();
- ты вызываешь `search_task($user_id)` два раза в этом коде. это не лучший вариант, так как каждый вызов функции у тебя вызывает запрос в базу.
- к тому же, если у тебя не выполняется условие `isset($_GET['search'])`, то искать и ничего не надо.
- у тебя сейчас в `$tasks` находятся либо найденные задачи, либо просто задачи юзера. это не позволяет в шаблоне тебе разобраться пришли ли задачи с поиска или это просто задачи юзера. выдели 2 переменные: `$found_tasks` - найденные и `$user_tasks` - задачи юзера. И потом уже аккуратно в шаблон их передай и в шаблоне обработай
- я предлагаю тебе сначала проверь `isset($_GET['search'])`. Если он есть, то заполнить `$found_tasks` ответами из базы. если его нет, то `$found_tasks` уже будут пустыми.

2021-04-27 11:57 UTC, mihan007 commented on functions/data.php
> +    $user_id = null;
сейчас isset можно вообще не использовать. его заменяет оператор `??`. эти 4 строки можно свернуть до одного `$user_id = $_SESSION['user_id'] ?? null`;

2021-04-27 11:57 UTC, mihan007 commented on functions/projects_and_tasks.php
> +    $user_id = $_SESSION['user_id'];
Лучше всего `user_id` определять в том месте кода, где понятно, что идет работа с веб-окружением. В нашем случае $user_id в эту функцию также должен передаваться.

2021-04-27 11:57 UTC, mihan007 commented on functions/search.php
> +    $searchString = $_GET['search'] ?? null;
- попробуй еще проще - в данном выражении используй тернарный оператор ? и тут же уже применяй trim.
- эту всю функцию можно написать в 3 строки и не использовать ни одного if. код будет чище и приятнее. попробуй

2021-04-27 11:57 UTC, mihan007 commented on pages/add.php
> +        user_id: $current_user_id,
удачное использование named params. так держать!

2021-04-27 11:57 UTC, mihan007 commented on templates/form_task.php
> +                <li class="main-navigation__list-item<?= is_active_project(
- так лучше не делать, слишком запутанно выходит - ты вызываешь функцию, она проверят $_GET. я бы сразу в шаблон уже передал $chosen_project_id и в этом месте просто проверял `if ($project['id'] == $chosen_project_id)` 
- вот смотри общую логику шаблонов - они должны оперировать только с переданными внутрь них данными. функции из них могут вызываться, но они должны быть максимально простыми и оперировать только с переданными в них параметрами. 
- Для одинакового набора параметров функция, вызываемая в шаблоне, всегда должна возвращать одинаковое значение. Такие функции называются "чистыми". Смотри https://ru.hexlet.io/courses/introduction_to_programming/lessons/pure/theory_unit
- В данном случае у тебя функция `is_active_project` не является чистой, так как внутри нее ты еще смотришь на $_GET. То есть ты его на вход не подаешь, но он у тебя прямо влияет на результат. Это усложняет как восприятие кода, так и его тестирование

2021-04-27 11:57 UTC, mihan007 commented on templates/main.php
> +                <li class="main-navigation__list-item<?= is_active_project(
и в этот шаблон тоже прямо передаем выбранный проект

2021-04-29 09:40 UTC, mihan007 requested changes
Осталось поправить `function search_task($user_id)` и посмотреть остальные функции - они не должны внутри себя работать с глобальными переменными. Глобальные переменные обрабатываются непосредственно в коде по генерации страницы и передаются внутрь функций.

2021-04-29 09:40 UTC, mihan007 commented on functions/search.php
> +function search_task($user_id): array|null
1. функция должна быть чистой. работа с $_GET и прочими глобальными переменными происходит извне функций, в скрипте обработки страницы. функция должна работать только с переданными в нее значения. В частности $searchString должно придти извне
2. определись с стилем наименования переменных. либо ты везде юзаешь через подчеркивание, это называется snake case: $var_name. либо везде новое слово с большой буквы. это называется camel Case. например, $varName. В этой функции у тебя смесь и того, и этого, так не стоит делать

2021-04-29 18:18 UTC, mihan007 approved these changes
принимаю. прекрасная работа. одну мелочь в следующем поправь, пожалуйста
```
function show_tasks($user_id): array
{
    $chosenProject = $_GET['id_chosen_project'] ?? null;
```

2021-04-29 18:18 UTC, merged