Завершение работы над проектом
htmlacademy-php/414045-doingsdone-12 pull request #15
Opened 2021-05-07 12:14 UTC by Archer039

2021-05-10 07:09 UTC, mihan007 requested changes
Роман, прекрасная работа! Хорошо разобрался в теме. Сделаем с тобой сессию рефакторинга и будем сдаваться. Жду)

2021-05-10 07:09 UTC, mihan007 commented on bootstrap.php
> +$chosen_tasks_filter = $_GET['tasks_filter'] ?? 'all';
лучше строковые значение, которые используются несколько раз по тексту программы, оформлять в виде констант и именно их использовать. это позволит допускать меньше ошибок и сделает легче рефакторинг. поэтому рекомендую
1. создать отдельный файл `constants.php`
2. в него вынести все статические строковые значения. например, у тебя будет `const TASK_FILTER_ALL_TASKS = 'all'`
3. использовать эту константу в коде. то есть `$chosen_tasks_filter = $_GET['tasks_filter'] ?? TASK_FILTER_ALL_TASKS;`

изучи остальные места - может где-то еще нужно

2021-05-10 07:09 UTC, mihan007 commented on bootstrap.php
> +    change_task_done_state($user_id, $task_id);
**Момент 1**
судя по всему, ты используешь гет параметр `check` для изменения статуса задачи. это неверный подход. 
- get параметры никогда не должны использоваться для внесения изменений в данные. для этого есть http глаголы post, put, patch, delete. 
- get параметр используется для получения данных. без их изменения. общее правило - get запрос с одними и теми же значениями get параметров должен выдавать одинаковый ответ. это называется умным словом идемпотентность. 

отсюда вывод - изменяем данный участок кода на post параметры 

**Момент 2**. ты действия бизнес логики делаешь в bootstrap.php. это в корне неверно. цель этого файла - подключить все другие файлы для обработки запроса. уноси код обработки события отметки файла в отдельный файл - обработчик страницы. и в html коде action формы будет отправлять у тебя на этот новый файл-обработчик страницы.

2021-05-10 07:09 UTC, mihan007 commented on bootstrap.php
> +    header('location: /');
Рекомендую тебе все header('....') функции вынести в отдельный файл и оформить их в функции. Тогда читаться будет легче и если у тебя поменяется роутинг, то изменения будут только в 1 файле. Например, тут получится что-то вроде
```
function redirect_to_home()
{
  header('location: /');
}
```

Более того - после отправки заголовка location через header тебе больше в коде ничего делать не надо, оно просто может не выполниться. поэтому я бы сразу прерывал выполнение кода после редиректа
```
redirect_to_home();
die;
```

2021-05-10 07:09 UTC, mihan007 commented on functions/check.php
> +            header('location: /error404/');
в файл redirect.php

2021-05-10 07:09 UTC, mihan007 commented on functions/check.php
>          if (!find_project_id($user_id, $id_chosen_project)) {
1. как правило, два подряд идущих if лучше оформлять в один.
2. функция должна делать ровно то, что записано в ее определении. у тебя записано `check_selected_project_id` - это значит, что она должна только проверить что-то, но ни в коем случае не менять логику работы программы через `redirect_to_not_found`.

Я бы оставил ее в виде
```
function check_selected_project_id($user_id, $id_chosen_project)
  return $id_chosen_project && !find_project_id($user_id, $id_chosen_project)
}
```

и уже внизу обработал результат ее ответа
```
// проверка id выбранного проекта
if (!check_selected_project_id($user_id, $chosen_project_id)) {
  redirect_to_not_found();
  die;
}
```

2021-05-10 07:09 UTC, mihan007 commented on functions/check.php
> +    if (find_project_id($user_id, $project_id)) {
смотри, если у тебя в функции if, фнукция возвращает true или false и кроме этого в теле цикла ничего не происходит, то надо упрощать функцию и возвращать сразу условие if. сейчас покажу как можно упростить эту функцию
```
function validate_project($project_id, $user_id)
{
    return find_project_id($user_id, $project_id);
}
```

2021-05-10 07:09 UTC, mihan007 commented on functions/check.php
> +    return $d && date_format($d, $format) == $date && $date >= date($format);
вот здесь хорошо сделал

2021-05-10 07:09 UTC, mihan007 commented on functions/projects_and_tasks.php
> +    if (!$project_id && (!$tasks_filter || $tasks_filter == 'all')) {
вот тут как раз `'all'` и заменится на константу `TASK_FILTER_ALL_TASKS`, о которой мы говорили выше

2021-05-10 07:09 UTC, mihan007 commented on functions/queries.php
> +    if (mysqli_stmt_error($stmt)) {
все же ошибка при запросе базы данных это серьезный повод закончить выполнение программы и упасть с ошибкой. поэтому рекомендую упростить код - падать при ошибке. тогда в местах, где ты вызываешь функции запроса к базе, тебе не надо результат обрабатывать - у тебя либо функция вернет результат, либо внутри себя уже упадет.

я бы код
```
if (mysqli_stmt_error($stmt)) {
        return false;
}
```
оформил в отдельную функцию
```
function query_ok_or_fail($stmt)
{
   if (!mysqli_stmt_error($stmt)) {
     return;
   }
   redirect_to_db_error_page();
   die;
}
```

и уже во всех этих функциях вызывал бы `query_ok_or_fail($stmt)`

2021-05-10 07:09 UTC, mihan007 commented on pages/add_project.php
> +    header('Location: /');
`redirect_to_home()`

2021-05-10 07:09 UTC, mihan007 commented on templates/form_task.php
> +       href="/?page=add_project" target="project_add">Добавить
подумай над роутингом. его надо делать единообразным. сейчас я вижу у тебя `/?page=add_project` и `/pages/add_task.php`. надо что-то одно. 

например, мне нравится вариант `/?page=add_project` переименовать в `/pages/add_project.php`

2021-05-10 07:09 UTC, mihan007 commented on templates/main.php
> +            <a href="/?tasks_filter=all<?= $chosen_project_id
такие работы над url лучше унести в отдельные функции. например, у тебя может появиться файл `route.php` с функциями вида
```
function get_url_all_project_tasks($chosen_project_id = null)
{
  return '/pages/tasks.php?task_filter=all' . 
    $chosen_project_id 
      ? "&id_chosen_project={$chosen_project_id}" 
      : ''
}
```

2021-05-13 08:36 UTC, Archer039 commented on bootstrap.php
> +$chosen_tasks_filter = $_GET['tasks_filter'] ?? 'all';
Создал constants.php, вынес строковые константы туда

2021-05-13 08:40 UTC, Archer039 commented on bootstrap.php
> +    change_task_done_state($user_id, $task_id);
1. поправил script.js часть кода закомментировал, чтобы не отправлял GET запрос с id проекта. Теперь при клике на чекбокс js создаёт форму и отправляет методом POST.
2. логику из bootstrap перенёс в scripts/change_task_state.php

2021-05-13 08:41 UTC, Archer039 commented on bootstrap.php
> +    header('location: /');
Создал redirect.php и в нём функции редиректа

2021-05-13 08:43 UTC, Archer039 commented on functions/check.php
> +    if (find_project_id($user_id, $project_id)) {
Поправил

2021-05-13 08:44 UTC, Archer039 commented on functions/queries.php
> +    if (mysqli_stmt_error($stmt)) {
Понял! Да, так гораздо удобнее)

2021-05-13 08:46 UTC, Archer039 commented on templates/form_task.php
> +       href="/?page=add_project" target="project_add">Добавить
Привёл всё к виду /pages/add_project.php
Пришлось немного поменять логику. В /pages теперь скрипты отвечающие за вывод шаблонов. Обработку форм и другие скрипты обработки перенёс в /scripts

2021-05-13 08:47 UTC, Archer039 commented on templates/main.php
> +            <a href="/?tasks_filter=all<?= $chosen_project_id
Создал route.php, перенёс туда

2021-05-13 09:37 UTC, mihan007 commented on script.js
> +// if ($taskCheckboxes.length) {
мертвый код убери в следующем PR, пожалуйста

2021-05-13 09:39 UTC, mihan007 commented on scripts/change_task_state.php
> +if ($_SERVER['REQUEST_METHOD'] == 'POST' && isset($_POST['id_task_for_state_changing'])) {
тут можно просто оставить `isset($_POST['id_task_for_state_changing'])`, так как $_POST будет пустым, если запрос не POST.

2021-05-13 09:41 UTC, mihan007 commented on templates/form_task.php
> +    <form class="form" action="/scripts/add_task.php" method="post"
теоретически везде, где есть url, можно эти url унести в routes.php и потом здесь уже вызывать функции. тогда в routes.php тебе достаточно будет вносить изменения, если поменяешь структуру проекта, а view можно будет не трогать. на твое усмотрение, это необязательно

2021-05-13 09:41 UTC, mihan007 approved these changes
Браво! Прекрасная работа!

2021-05-13 09:42 UTC, merged