Исправил замечания
htmlacademy-php/414045-doingsdone-12 pull request #19
Opened 2021-05-22 19:12 UTC by Archer039

2021-05-23 05:51 UTC, mihan007 requested changes
Хорошо привёл в порядок.

Предлагаю ещё доработать: 
1. вынести magic numbers в константы(погугли антипаттерн magic numbers)
2. везде, где у тебя код внутри if - пробуй оптимизировать через if (!...), чтобы уменьшить вложенность

2021-05-23 05:51 UTC, mihan007 commented on functions/check.php
> +    return ((int)$_FILES['file']['error'] === 0 || (int)$_FILES['file']['error'] === 4);
Вынести 0 и 4 в константы

2021-05-23 05:51 UTC, mihan007 commented on functions/check.php
> +    if (strlen($task_name) > 64) {
64 в константу

2021-05-23 05:51 UTC, mihan007 commented on functions/check.php
> +    if (strlen($_FILES['file']['name']) > 64) {
64 константа

2021-05-23 05:51 UTC, mihan007 commented on functions/check.php
> +    if (strlen($project_name) > 20) {
20 константа

2021-05-23 05:51 UTC, mihan007 commented on functions/check.php
> +    if (!$email || strlen($email) > 128) {
128 const

2021-05-23 05:51 UTC, mihan007 commented on functions/check.php
> +    if (!$password || strlen($password) < 4 || strlen($password) > 64) {
4 const

2021-05-23 05:51 UTC, mihan007 commented on functions/check.php
> +    if (!$name || strlen($name) > 64) {
64 const

2021-05-23 05:51 UTC, mihan007 commented on functions/data.php
>      if ($errors) {
Может быть попробовать if (!..), чтобы убрать вложенность?

2021-05-23 05:51 UTC, mihan007 commented on functions/data.php
>      if ($errors) {
If (!..

2021-05-23 05:51 UTC, mihan007 commented on functions/data.php
> +    if ($errors) {
if (!..)

2021-05-23 05:51 UTC, mihan007 commented on functions/projects_and_tasks.php
>      if ($file['name']) {
Попробовать if (!..)

2021-05-23 05:51 UTC, mihan007 commented on functions/queries.php
> +    if ((string)$time_end === '') {
Лучше if (empty(...))

2021-05-23 05:51 UTC, mihan007 commented on functions/redirect.php
> +    header('location: /pages/db_error_page.php?error=' . $error);
Может вынести адрес страницы в routes.php?

2021-05-24 13:49 UTC, Archer039 commented on functions/check.php
> +    return ((int)$_FILES['file']['error'] === 0 || (int)$_FILES['file']['error'] === 4);
Что-то затупил, уже есть в php такие константы)  UPLOAD_ERR_OK и UPLOAD_ERR_NO_FILE

2021-05-24 14:31 UTC, Archer039 commented on functions/data.php
>      if ($errors) {
Не совсем понял как там можно упростить

2021-05-24 14:32 UTC, Archer039 commented on functions/projects_and_tasks.php
>      if ($file['name']) {
Тут понял

2021-05-24 19:39 UTC, mihan007 commented
🤘

2021-05-24 19:39 UTC, merged