добавил функцию для подсчета количества дел по проектам
htmlacademy-php/414045-doingsdone-12 pull request #4
Opened 2021-01-26 10:42 UTC by Archer039

2021-01-26 11:14 UTC, mihan007 requested changes
Роман, смотри. Это задание я могу принять, если захочешь, ты его сделал верно.

Однако, я там тебе выдал задачку со звездочкой - как ту же функцию написать с приемами из функционального программирования. Функциональный подход очень красивый и лаконичный. Попробуй эту задачу сделать. Маякуй, что решишь и нужна ли помощь с решением задачи.

2021-01-26 11:14 UTC, mihan007 commented on index.php
> +    $count_project = 0;
Этот вариант хороший. Для расширения кругозора попробуй эту же функцию сделать через array_reduce. Тебе понадобятся
- https://www.php.net/manual/ru/function.array-reduce.php
- https://www.php.net/manual/ru/functions.anonymous.php

Подсказка есть в https://www.php.net/manual/ru/function.array-reduce.php#124471

2021-01-26 16:43 UTC, mihan007 requested changes
Хорошая работа! И еще чутка полирнем)

2021-01-26 16:43 UTC, mihan007 commented on index.php
> +                                0
попробуй здесь через оператор ?? (null coalescing)
https://riptutorial.com/php/example/7164/null-coalescing-operator-----

2021-01-26 16:43 UTC, mihan007 commented on index.php
> +$project_count = array_reduce($tasks, function($carry, $item){
ход мыслей верный, но получилась не функция)

надо, чтобы ее вызывали так:
$count = get_project_count($category_name);
и в $count у тебя после этого должно быть количество задач в категории.

2021-01-26 18:42 UTC, Archer039 commented on index.php
> +                                0
Классный оператор, да так удобнее)

2021-01-26 18:48 UTC, Archer039 commented on index.php
> +$project_count = array_reduce($tasks, function($carry, $item){
Вот тут тогда вопрос, если обернуть array_reduce() в функцию, в функцию помимо названия категории нужно будет передавать ещё и массив, который будет обрабатывать array_reduce(), иначе он не будет в области видимости, правильно?

2021-01-27 18:36 UTC, mihan007 approved these changes
Все по красоте, отличная работа!

2021-01-27 18:36 UTC, mihan007 commented on index.php
> +
хорошее решение. если есть желание - напиши в телегу, поделюсь своим

2021-01-28 13:41 UTC, merged